[package]
name = "releasaurus"
version = "0.3.12"
edition = "2024"
description = "A comprehensive release automation tool that streamlines the software release process across multiple programming languages and forge platforms"
repository = "https://github.com/robgonnella/releasaurus"
homepage = "https://releasaurus.rgon.io"
license  = "MIT OR Apache-2.0"
keywords = ["release", "semver", "conventional", "commits", "changelog"]
categories = ["command-line-utilities", "development-tools"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "releasaurus"
path = "src/main.rs"

[[bin]]
name = "generate-schema"
path = "scripts/gen_schema.rs"

[dependencies]
clap = { version = "4.5.45", features = ["derive"]}
color-eyre = "0.6.5"
git2 = "0.20.2"
git-url-parse = "0.4.5"
log = "0.4.27"
octocrab = "0.45.0"
quick-xml = "0.36.2"
regex = "1.11.1"
reqwest = "0.12.23"
secrecy = "0.10.3"
serde = { version = "1.0.219" }
serde_json = { version = "1.0.143", features = ["preserve_order"] }
simplelog = { version = "0.12.2" }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs"] }
toml = "0.9.5"
semver = "1.0.26"
toml_edit = "0.23.4"
next_version = "0.2.24"
git-conventional = "0.12.9"
tera = "1.20.0"
chrono = "0.4.42"
async-trait = "0.1.89"
gitlab = "0.1805.0"
base64 = "0.22.1"
graphql_client = "0.14.0"
schemars = "1.1.0"

[dev-dependencies]
mockall = "0.13.1"
nanoid = "0.4.0"
paste = "1.0"
