#:schema ./schema/schema.json

[changelog]
skip_ci = true
skip_chore = true
skip_miscellaneous = false
include_author = true

[[package]]
release_type = "rust"
additional_manifest_files = [
  { path = "./action/action.yml", version_regex = "v(?<version>\\d\\.\\d\\.\\d)" }
]
