name: publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  gh-pages:
    concurrency: publish-gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: peaceiris/actions-mdbook@v2
      - run: cd book && mdbook build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          cname: releasaurus.rgon.io

  docker:
    concurrency: publish-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: rgonnella/releasaurus
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  crate:
    concurrency: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  binaries:
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: MacOS-arm
            runs-on: macOS-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Install Target Dependencies
        run: |
          case ${{ matrix.target }} in
            x86_64-unknown-linux-musl)
              sudo apt update
              sudo apt install openssl build-essential musl-tools musl-dev libssl-dev
              ;;
            aarch64-unknown-linux-musl)
              sudo apt update
              sudo apt install openssl build-essential musl-tools musl-dev libssl-dev:arm64
              ;;
          esac

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0
        with:
          targets: ${{ matrix.target }}

      - name: Build with cross
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TEST_TOKEN }}
          file_glob: true
          file: target/${{ matrix.target }}/release/${{ github.event.repository.name }}*
          tag: ${{ github.ref }}
          overwrite: false
