name: publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-gh-pages:
    concurrency: publish-gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: peaceiris/actions-mdbook@v2
      - run: cd book && mdbook build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          cname: releasaurus.rgon.io

  publish-docker:
    concurrency: publish-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: rgonnella/releasaurus
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  publish-crate:
    concurrency: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  package-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: releasaurus

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact: releasaurus

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: releasaurus.exe

          - os-name: MacOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            artifact: releasaurus
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Add tag to env
        run: |
          TAG_WITH_PREFIX="${{ github.ref }}"
          TAG_NAME="${TAG_WITH_PREFIX#refs/tags/}"
          echo "Full Ref: $TAG_WITH_PREFIX"
          echo "Tag Name: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV # Make it available to subsequent steps

      - name: Build with cross
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          toolchain: 1.90.0
          target: ${{ matrix.platform.target }}
          args: "--locked --release"

      - name: Package
        run: |
          PACKAGE_DIR=releasaurus-${{ env.TAG_NAME }}-{{ matrix.platform.target }}
          PACKAGE="${PACKAGE_DIR}.tgz"
          mkdir -p $PACKAGE_DIR
          cp ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.artifact }} $PACKAGE_DIR
          tar -czvf $PACKAGE $PACKAGE_DIR
          echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PACKAGE }}
          path: ${{ env.PACKAGE }}

  update-release:
    runs-on: ubuntu-latest
    needs: package-binaries
    steps:
      - name: Create packages dir
        run: mkdir -p /root/packages
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: "*.tgz"
          path: /root/packages
          merge-multiple: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TEST_TOKEN }}
          file_glob: true
          file: /root/packages/*.tgz
