name: publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-gh-pages:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    concurrency: publish-gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: peaceiris/actions-mdbook@v2
      - run: cd book && mdbook build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          cname: releasaurus.rgon.io

  publish-crate:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    concurrency: publish-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  package-binaries:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            executable: releasaurus

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl
            executable: releasaurus

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            executable: releasaurus.exe

          - os-name: MacOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            executable: releasaurus
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build with cross
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          toolchain: 1.90.0
          target: ${{ matrix.platform.target }}
          args: "--locked --release"

      - name: Package
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          files: |
            ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.executable }}
          outPath: releasaurus-${{ github.ref_name }}-${{ matrix.platform.target }}.tgz

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: releasaurus-${{ github.ref_name }}-${{ matrix.platform.target }}.tgz
          path: releasaurus-${{ github.ref_name }}-${{ matrix.platform.target }}.tgz

  update-release:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    runs-on: ubuntu-latest
    needs: package-binaries
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: "*.tgz"
          path: ./dist/
          merge-multiple: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TEST_TOKEN }}
          file_glob: true
          file: ./dist/*.tgz

  publish-docker:
    if: ${{ github.repository == 'robgonnella/releasaurus' }}
    concurrency: publish-docker
    runs-on: ubuntu-latest
    needs: update-release
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: rgonnella/releasaurus
      - id: version
        run: |
          tag=${{ steps.meta.outputs.version }}
          semver=${tag##*v}
          echo "semver=$semver" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          build-args: RELEASAURUS_VERSION=${{ steps.version.outputs.semver }}

  test-action:
    runs-on: ubuntu-latest
    needs: publish-docker
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: get next-release
        uses: ./action
        with:
          command: get
          command_args: >-
            next-release
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
      - name: release (dry-run)
        uses: ./action
        with:
          command: release
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run
      - name: release-pr (dry-run)
        uses: ./action
        with:
          command: release-pr
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run
      - name: start-next (dry-run)
        uses: ./action
        with:
          command: start-next
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run
