name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-unit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
        with:
          cache_name: test-unit
          include_llvm_cov: "true"
      - name: test
        run: |
          cargo llvm-cov --ignore-filename-regex "(_test\.rs$)|(_tests\.rs$)"

  test_all:
    runs-on: ubuntu-latest
    if: github.repository == 'robgonnella/releasaurus' && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
        with:
          cache_name: test-integration
          include_llvm_cov: "true"
      - name: test
        env:
          GITHUB_TEST_REPO: https://github.com/robgonnella/test-repo
          GITHUB_TEST_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
          GITHUB_RESET_SHA: 54d2a06b1c60f63001dc20d5977dbb1e288572df
          GITLAB_TEST_REPO: https://gitlab.com/rgon/test-repo
          GITLAB_TEST_TOKEN: ${{ secrets.GL_TEST_TOKEN }}
          GITLAB_RESET_SHA: dad21fa1cdfb5a3ac2624de4ae8c055668139dc1
          GITEA_TEST_REPO: https://gitea.com/rgon/test-repo
          GITEA_TEST_TOKEN: ${{ secrets.GT_TEST_TOKEN }}
          GITEA_RESET_SHA: b353e2f4128a9436540e4f2ddefd9989a9633372
        run: |
          cargo llvm-cov \
            --ignore-filename-regex "(_test\.rs$)|(_tests\.rs$)" \
            --features _integration_tests

  test-action:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - name: show next-release
        uses: ./action
        with:
          command: show
          command_args: >-
            next-release
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug

      - name: release (dry-run)
        uses: ./action
        with:
          command: release
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run

      - name: release-pr (dry-run)
        uses: ./action
        with:
          command: release-pr
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run

      - name: start-next (dry-run)
        uses: ./action
        with:
          command: start-next
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
            --base-branch ${{ github.head_ref || github.ref_name }}
            --debug
            --dry-run
