name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: build
        run: cargo build --release

  check-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: generate
        run: cargo run --bin generate-schema
      - name: check
        run: |
          if ! git diff --exit-code; then
            git status
            echo "❌ Error: Uncommitted changes detected after running generate-schema script."
            echo "❌ Please run \"cargo run --bin generate-schema\" and commit changes"
            exit 1
          else
            echo "✅ Schema is up-to-date"
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: lint
        run: cargo clippy --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: fmt
        run: cargo fmt --all --check

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: test
        env:
          GH_TEST_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
          GL_TEST_TOKEN: ${{ secrets.GL_TEST_TOKEN }}
          GT_TEST_TOKEN: ${{ secrets.GT_TEST_TOKEN }}
        run: |
          git config --global user.name "github-ci"
          git config --global user.email "github-ci@ci.com"
          git config --global init.defaultBranch main
          cargo llvm-cov --ignore-filename-regex "(_test\.rs$)|(_tests\.rs$)"

  test-e2e:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false && github.ref_name == github.event.repository.default_branch
    concurrency:
      group: e2e-tests
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust-setup
      - name: test
        env:
          GH_TEST_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
          GL_TEST_TOKEN: ${{ secrets.GL_TEST_TOKEN }}
          GT_TEST_TOKEN: ${{ secrets.GT_TEST_TOKEN }}
        run: |
          git config --global user.name "github-ci"
          git config --global user.email "github-ci@ci.com"
          cargo test --features _internal_e2e_tests e2e_test
